function TsunamisData = importData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  TSUNAMISDATA = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  TSUNAMISDATA = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  TSUNAMISDATA = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TsunamisData = importfile("C:\Users\agarcian\OneDrive - MathWorks\Documents\CSE Info\Presentations\For Datathons\modeling-tsunami-intensity\TsunamiIntensityModel\TsunamisData.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Oct-2023 16:10:59

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 18);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Latitude", "Longitude", "Year", "Month", "Day", "Hour", "Minute", "Second", "ValidityCode", "Validity", "CauseCode", "Cause", "EarthquakeMagnitude", "Country", "Location", "MaxHeight", "IidaMagnitude", "Intensity"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "categorical", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Validity", "Cause", "Country", "Location"], "EmptyFieldRule", "auto");

% Import the data
TsunamisData = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    TsunamisData = [TsunamisData; tb]; %#ok<AGROW>
end

end